FROM jupyter-docker-base-image:201804191153

LABEL maintainer="Christian Schuhegger <christian.schuhegger@gmx.de>"

USER root

RUN ln -s /bin/tar /bin/gtar

USER $NB_UID

COPY pycharm-professional-2018.1.2.tar.gz $HOME/
RUN tar -xzvf pycharm-professional-2018.1.2.tar.gz
ENV PATH "$PATH:$HOME/pycharm-2018.1.2/bin"
