FROM jupyter-docker-base-image:201812030859

LABEL maintainer="Christian Schuhegger <christian.schuhegger@gmx.de>"

USER $NB_UID

COPY pycharm-professional-2018.1.2.tar.gz $HOME/
RUN tar -xzvf pycharm-professional-2018.1.2.tar.gz
ENV PATH "$PATH:$HOME/pycharm-2018.1.2/bin"
