name: py38ds
channels:
  - numba
  - astropy
  - pyviz
  - r
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy #=1.15.4
  - scipy #=1.1.0
  - pandas #=0.23.4
  - pytables #=3.4.4
  - h5py #=2.9.0
  - statsmodels
  - scikit-learn #=0.20.1
  - scikit-learn-intelex # python -m sklearnex my_application.py # https://intel.github.io/scikit-learn-intelex/
  - matplotlib #=3.0.1
  - seaborn #=0.9.0
  - pytest #=4.0.1
  - xlrd #=1.1.0
  - openpyxl #=2.5.11
  - xlwt #=1.3.0
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - mkl-service #=1.1.2
  - zlib #=1.2.11
  - nltk #=3.3.0
  - sympy #=1.3
  - numba #=0.42.0
  - numba-scipy
  - jupyter #=1.0.0
  - cython #=0.29.5
  - bioconda::pycluster
  - astropy
  - astroML
  - zlib #=1.2.11
  - holoviews
  - bokeh
  - cvxopt
  - domosute::quantlib # conda install -c domosute quantlib
  - domosute::quantlib-python # conda install -c domosute quantlib-python
  - r-essentials=3.6.0
  # - rpy2 #=2.9.4
  - r-tidyverse=1.2.1
  - r-lubridate=1.7.4
  - r-networkd3=0.4
  - r-printr
  - r-rmarkdown
  - r-psych
  - r-bnlearn
  - r-gparotation
  - r-corrplot
  # - tensorflow-gpu=2.4.1
  # - pytorch=1.9.0
  # - torchvision
  # - torchaudio
  # - cudatoolkit=10.2
