name: jupyter-docker-base-image
channels:
  - defaults
dependencies:
  - pip
  - numpy=1.15.4
  - scipy=1.1.0
  - pandas=0.23.4
  - scikit-learn=0.20.1
  - matplotlib=3.0.1
  - seaborn=0.9.0
  - xlrd=1.1.0
  - pytest=4.0.1
  - openpyxl=2.5.11
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - mkl-service=1.1.2
  - zlib=1.2.11
  - nltk=3.3.0
  - pip:
    - gpy==1.9.6
    - lifelines==0.15.1
    - minepy==1.2.2
    - graphviz==0.10.1
    - requests==2.20.1


