name: jupyter-docker-base-image
channels:
  - defaults
dependencies:
  - pip
  - numpy=1.14.2
  - scipy=1.0.1
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - matplotlib=2.2.2
  - seaborn=0.8.1
  - xlrd=1.1.0
  - pytest=3.5.0
  - openpyxl=2.5.1
  - pip:
    - pip==10.0.0
    - gpy==1.9.2
