
install.packages("devtools")
devtools::install_github("ottlngr/LexisPlotR", force = TRUE)
install.packages("printr")
source("https://bioconductor.org/biocLite.R")
biocLite("graph")
biocLite("RBGL")
#install.packages("graph")
#install.packages("RBGL")
install.packages("gRbase")
install.packages("gRain")
#install.packages("networkD3")
# install.packages("tidyverse")
# install.packages("lubridate")
