

jupyter-docker-base-image:
	docker build --build-arg HTTP_PROXY=${HTTP_PROXY} --build-arg HTTPS_PROXY=${HTTPS_PROXY} --tag jupyter-docker-base-image:201804191153 --tag jupyter-docker-base-image:latest .
